server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: compras-service
          uri: lb://compras-service
          predicates:
            - Path=/orden-compra/**
        - id: sharksales-monolith-ventas
          uri: lb://sharksales-monolith
          predicates:
              - Path=/ordenventa/**
        - id: sharksales-monolith-proveedores
          uri: lb://sharksales-monolith
          predicates:
            - Path=/proveedores/**
        - id: sharksales-monolith-productos
          uri: lb://sharksales-monolith
          predicates:
            - Path=/productos/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8231/eureka/
    registerWithEureka: true